"""empty message

Revision ID: 973b4a285c70
Revises: 27cddcc0f220
Create Date: 2025-12-02 10:48:25.723747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973b4a285c70'
down_revision = '27cddcc0f220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
